// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613161752_AddDeviceEntity")]
    partial class AddDeviceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webapi.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceLocation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_location");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_name");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModel")
                        .IsUnique()
                        .HasDatabaseName("idx_devices_device_model");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("webapi.Models.InspectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_model");

                    b.Property<string>("DeviceName")
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("日")
                        .HasColumnName("frequency");

                    b.Property<DateTime>("InspectionTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inspection_time");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("")
                        .HasColumnName("period_key");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("results_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModel", "Frequency", "PeriodKey")
                        .IsUnique()
                        .HasDatabaseName("idx_records_period");

                    b.ToTable("inspection_records", (string)null);
                });

            modelBuilder.Entity("webapi.Models.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsNormal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_normal");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("item_name");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("result_value");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("inspection_results", (string)null);
                });

            modelBuilder.Entity("webapi.Models.InspectionSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Approver")
                        .HasColumnType("longtext")
                        .HasColumnName("approver");

                    b.Property<string>("Confirmer")
                        .HasColumnType("longtext")
                        .HasColumnName("confirmer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_model");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<string>("OperatorName")
                        .HasColumnType("longtext")
                        .HasColumnName("operator_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("inspection_signatures");
                });

            modelBuilder.Entity("webapi.Models.InspectionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_model");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("日")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_mandatory");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("item_type");

                    b.Property<decimal?>("NormalMax")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("normal_max");

                    b.Property<decimal?>("NormalMin")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("normal_min");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("inspection_templates", (string)null);
                });

            modelBuilder.Entity("webapi.Models.InspectionUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("inspection_users", (string)null);
                });

            modelBuilder.Entity("webapi.Models.QualifiedInspector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("employee_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("idx_qualified_inspectors_employee_id");

                    b.ToTable("qualified_inspectors", (string)null);
                });

            modelBuilder.Entity("webapi.Models.InspectionResult", b =>
                {
                    b.HasOne("webapi.Models.InspectionRecord", "InspectionRecord")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
